/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.tienda.animalapp.layer.view;

import java.awt.Image;
import java.net.URL;
import java.net.URLConnection;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.tienda.animalapp.controller.AnimalController;
import pe.tienda.animalapp.controller.TrabajadorController;
import pe.tienda.animalapp.gravatar.MD5Util;

/**
 *
 * @author Alumno-CT
 */
public class TrabajadorView extends javax.swing.JFrame {
    DefaultTableModel tabla;
    /**
     * Creates new form TrabajadorView
     */
    public TrabajadorView() {
        initComponents();
        initControls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        pnlPrincipal = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JPanel();
        lbltipo = new javax.swing.JLabel();
        rbnvaca = new javax.swing.JRadioButton();
        rbncaballo = new javax.swing.JRadioButton();
        rbngallina = new javax.swing.JRadioButton();
        rbnpollo = new javax.swing.JRadioButton();
        lbltipo1 = new javax.swing.JLabel();
        txtCantidadAnimal = new javax.swing.JTextField();
        lbltipo2 = new javax.swing.JLabel();
        txtPrecioUnidad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtNombreVendedor = new javax.swing.JTextField();
        txtNombreComprador = new javax.swing.JTextField();
        cboCargo = new javax.swing.JComboBox();
        txtRuc = new javax.swing.JTextField();
        lbltipo3 = new javax.swing.JLabel();
        lbltipo4 = new javax.swing.JLabel();
        lbltipo5 = new javax.swing.JLabel();
        lbltipo6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnFinaliza = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbltipo7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnAcceder = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mnuprincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mniCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestor de Sueldos");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        txtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Animal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(51, 51, 255));

        lbltipo.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo.setText("Tipo");

        rbnvaca.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbnvaca);
        rbnvaca.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbnvaca.setText("Vaca");
        rbnvaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnvacaActionPerformed(evt);
            }
        });

        rbncaballo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbncaballo);
        rbncaballo.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbncaballo.setText("Caballo");

        rbngallina.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbngallina);
        rbngallina.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbngallina.setText("Gallina");

        rbnpollo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbnpollo);
        rbnpollo.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbnpollo.setText("Pollo");

        lbltipo1.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo1.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo1.setText("Cantidad");

        lbltipo2.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo2.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo2.setText("Precio por Unidad");

        javax.swing.GroupLayout txtCantidadLayout = new javax.swing.GroupLayout(txtCantidad);
        txtCantidad.setLayout(txtCantidadLayout);
        txtCantidadLayout.setHorizontalGroup(
            txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltipo)
                    .addComponent(rbncaballo)
                    .addComponent(rbnpollo)
                    .addComponent(rbngallina)
                    .addComponent(rbnvaca))
                .addGap(61, 61, 61)
                .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbltipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbltipo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidadAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        txtCantidadLayout.setVerticalGroup(
            txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantidadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtCantidadLayout.createSequentialGroup()
                        .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltipo)
                            .addComponent(lbltipo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnpollo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnvaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbncaballo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbngallina))
                    .addGroup(txtCantidadLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtCantidadAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbltipo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        tblData.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMPRADOR", "RUC", "VENDEDOR", "ANIMAL", "CANTIDAD", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);
        tblData.getColumnModel().getColumn(0).setResizable(false);
        tblData.getColumnModel().getColumn(1).setResizable(false);
        tblData.getColumnModel().getColumn(2).setResizable(false);
        tblData.getColumnModel().getColumn(3).setResizable(false);
        tblData.getColumnModel().getColumn(4).setResizable(false);
        tblData.getColumnModel().getColumn(5).setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Vendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        cboCargo.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cboCargo.setForeground(new java.awt.Color(0, 0, 255));
        cboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCargo.setToolTipText("Tipo de Trabador en la Venta");
        cboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCargoActionPerformed(evt);
            }
        });

        lbltipo3.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo3.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo3.setText("Nombre Trabajador");

        lbltipo4.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo4.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo4.setText("Nombre Comprador");

        lbltipo5.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo5.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo5.setText("Cargo");

        lbltipo6.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo6.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo6.setText("RUC");

        btnAgregar.setBackground(new java.awt.Color(0, 102, 255));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnFinaliza.setBackground(new java.awt.Color(51, 102, 0));
        btnFinaliza.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnFinaliza.setForeground(new java.awt.Color(255, 255, 255));
        btnFinaliza.setText("Finalizar");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltipo6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltipo3)
                    .addComponent(lbltipo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipo4)
                    .addComponent(lbltipo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFinaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtTitulo.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 51, 255));
        txtTitulo.setText("Sistema Gestor de Venta de Animales");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mi Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        lbltipo7.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltipo7.setForeground(new java.awt.Color(51, 102, 255));
        lbltipo7.setText("Correo");

        btnAcceder.setBackground(new java.awt.Color(204, 204, 204));
        btnAcceder.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAcceder)
                            .addComponent(lbltipo7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(89, 89, 89))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbltipo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcceder))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        mnuprincipal.setBackground(new java.awt.Color(255, 255, 255));
        mnuprincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        mnuprincipal.setForeground(new java.awt.Color(255, 255, 255));
        mnuprincipal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jMenu1.setText("Inicio");
        mnuprincipal.add(jMenu1);

        jMenu2.setText("Acerca de");

        mniCreditos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mniCreditos.setText("Autor");
        mniCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreditosActionPerformed(evt);
            }
        });
        jMenu2.add(mniCreditos);

        mnuprincipal.add(jMenu2);

        setJMenuBar(mnuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCargoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cboCargoActionPerformed

    private void rbnvacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnvacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnvacaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Variables
        try {
            String nombreVendedor, nombreComprador, cargo="", ruc="-", tipoAnimal;
            int cantidad;
            double precio;
            Map<String, Double> rptaAnimal;
            nombreVendedor=txtNombreVendedor.getText();
            nombreComprador=txtNombreComprador.getText();
            tipoAnimal= this.buttonGroup1.getSelection().getActionCommand();
            cantidad= Integer.parseInt(txtCantidadAnimal.getText());
            cargo = this.cboCargo.getSelectedItem().toString();
            precio=Double.parseDouble(txtPrecioUnidad.getText());
            ruc=txtRuc.getText();
            //Proceso
            AnimalController Ani= new AnimalController();
            rptaAnimal= Ani.procesar(tipoAnimal,cantidad);
            //Mostrar
            Object[] rowData={nombreComprador, ruc, nombreVendedor,tipoAnimal, cantidad, rptaAnimal.get("Total")};        
            tabla = (DefaultTableModel) this.tblData.getModel();
            tabla.addRow(rowData);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Complete todo el formulario desde aqui.");
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed
        try {
            FinalizadoDiaView finaldia=new FinalizadoDiaView(null, true);
            finaldia.setVisible(true);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Complete todo el formulario.");
        }
        
    }//GEN-LAST:event_btnFinalizaActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        URL url;
        URLConnection urlCon;
        ImageIcon icon;
        ImageIcon icono;
        String email=txtemail.getText();
        try {
            //67692b385cc73f1b6d6bcb24b13bfc37
            String hash = MD5Util.md5Hex(email.toLowerCase());
            url = new URL("http://www.gravatar.com/avatar/"+hash);
            urlCon = url.openConnection();
            icon = new ImageIcon(url);
            icono = new ImageIcon(icon.getImage().getScaledInstance(label2.getWidth(), label2.getHeight(), Image.SCALE_DEFAULT));
            label2.setIcon(icono);
            label2.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Problemas de conexion a Internet");
        }
    }//GEN-LAST:event_btnAccederActionPerformed

    private void mniCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreditosActionPerformed
        // TODO add your handling code here:
        try {
            
            CreditosView credito=new CreditosView(null, true);
            credito.setVisible(true);
        }catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Error al cargar.");
        }
    }//GEN-LAST:event_mniCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrabajadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrabajadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrabajadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabajadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TrabajadorView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboCargo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JLabel lbltipo1;
    private javax.swing.JLabel lbltipo2;
    private javax.swing.JLabel lbltipo3;
    private javax.swing.JLabel lbltipo4;
    private javax.swing.JLabel lbltipo5;
    private javax.swing.JLabel lbltipo6;
    private javax.swing.JLabel lbltipo7;
    private javax.swing.JMenuItem mniCreditos;
    private javax.swing.JMenuBar mnuprincipal;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JRadioButton rbncaballo;
    private javax.swing.JRadioButton rbngallina;
    private javax.swing.JRadioButton rbnpollo;
    private javax.swing.JRadioButton rbnvaca;
    private javax.swing.JTable tblData;
    private javax.swing.JPanel txtCantidad;
    private javax.swing.JTextField txtCantidadAnimal;
    private javax.swing.JTextField txtNombreComprador;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtPrecioUnidad;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables

    private void initControls() {
        //radio Button
        this.rbncaballo.setActionCommand(AnimalController.TIPO_CABALLO);
        this.rbnvaca.setActionCommand(AnimalController.TIPO_VACA);
        this.rbngallina.setActionCommand(AnimalController.TIPO_GALLINA);
        this.rbnpollo.setActionCommand(AnimalController.TIPO_POLLO);
        //combo
        this.cboCargo.removeAllItems();
        TrabajadorController controller = new TrabajadorController();
        for(String item: controller.obtenerCargos()){
            this.cboCargo.addItem(item);
        }
        //Tabla
        
    }
}
