/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.tienda.animalapp.layer.view;

import java.awt.Image;
import java.net.URL;
import java.net.URLConnection;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.tienda.animalapp.controller.AnimalController;
import pe.tienda.animalapp.controller.TrabajadorController;
import pe.tienda.animalapp.gravatar.MD5Util;

public class WorkerView extends javax.swing.JFrame {
    DefaultTableModel table;
    /**
     * Creates new form WorkerView
     */
    public WorkerView() {
        initComponents();
        initControls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jProgressBar1 = new javax.swing.JProgressBar();
    pnlPrincipal = new javax.swing.JPanel();
    txtQuantity = new javax.swing.JPanel();
    lblType = new javax.swing.JLabel();
    rbnCow = new javax.swing.JRadioButton();
    rbnHorse = new javax.swing.JRadioButton();
    rbnRooster = new javax.swing.JRadioButton();
    rbnChicken = new javax.swing.JRadioButton();
    lblAmount = new javax.swing.JLabel();
    txtAnimalQuantity = new javax.swing.JTextField();
    lblPricePerUnit = new javax.swing.JLabel();
    txtUnitPrice = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblData = new javax.swing.JTable();
    jPanel4 = new javax.swing.JPanel();
    txtSellerName = new javax.swing.JTextField();
    txtBuyerName = new javax.swing.JTextField();
    cboPosition = new javax.swing.JComboBox();
    txtRuc = new javax.swing.JTextField();
    lblWorkerName = new javax.swing.JLabel();
    lblBuyerName = new javax.swing.JLabel();
    lblPosition = new javax.swing.JLabel();
    lblRuc = new javax.swing.JLabel();
    btnAdd = new javax.swing.JButton();
    btnSubmit = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    txtTitle = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    lblEmail = new javax.swing.JLabel();
    txtEmail = new javax.swing.JTextField();
    btnAccess = new javax.swing.JButton();
    label2 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    jSeparator3 = new javax.swing.JSeparator();
    mainMenu = new javax.swing.JMenuBar();
    menuFile = new javax.swing.JMenu();
    menuEdit = new javax.swing.JMenu();
    menuItemCredits = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Salary Management System");
    setBackground(new java.awt.Color(255, 255, 255));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

    txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
    txtQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N
    txtQuantity.setForeground(new java.awt.Color(51, 51, 255));

    lblType.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    lblType.setForeground(new java.awt.Color(51, 102, 255));
    lblType.setText("Type");

    rbnCow.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(rbnCow);
    rbnCow.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
    rbnCow.setText("Cow");
    rbnCow.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbnCowActionPerformed(evt);
        }
    });

    rbnHorse.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(rbnHorse);
    rbnHorse.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
    rbnHorse.setText("Horse");
    rbnHorse.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbnHorseActionPerformed(evt);
        }
    });

    rbnRooster.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(rbnRooster);
    rbnRooster.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
    rbnRooster.setText("Rooster");
    rbnRooster.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbnRoosterActionPerformed(evt);
        }
    });

    rbnChicken.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(rbnChicken);
    rbnChicken.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
    rbnChicken.setText("Chicken");
    rbnChicken.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbnChickenActionPerformed(evt);
        }
    });

    lblAmount.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    lblAmount.setForeground(new java.awt.Color(51, 102, 255));
    lblAmount.setText("Amount");

    lblPricePerUnit.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    lblPricePerUnit.setForeground(new java.awt.Color(51, 102, 255));
    lblPricePerUnit.setText("Price/unit");

    javax.swing.GroupLayout txtQuantityLayout = new javax.swing.GroupLayout(txtQuantity);
    txtQuantity.setLayout(txtQuantityLayout);
    txtQuantityLayout.setHorizontalGroup(
        txtQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(txtQuantityLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(txtQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblType)
                .addComponent(rbnHorse)
                .addComponent(rbnChicken)
                .addComponent(rbnRooster)
                .addComponent(rbnCow))
            .addGap(61, 61, 61)
            .addGroup(txtQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPricePerUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnimalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(232, Short.MAX_VALUE))
    );
    txtQuantityLayout.setVerticalGroup(
        txtQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(txtQuantityLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(txtQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtQuantityLayout.createSequentialGroup()
                    .addGroup(txtQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblType)
                        .addComponent(lblAmount))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rbnChicken)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rbnCow)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rbnHorse)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rbnRooster))
                .addGroup(txtQuantityLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(txtAnimalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblPricePerUnit)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(41, 41, 41))
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

    tblData.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    tblData.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "BUYER", "RUC", "SELLER", "ANIMAL", "AMOUNT", "TOTAL"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane1.setViewportView(tblData);
    if (tblData.getColumnModel().getColumnCount() > 0) {
        tblData.getColumnModel().getColumn(0).setResizable(false);
        tblData.getColumnModel().getColumn(1).setResizable(false);
        tblData.getColumnModel().getColumn(2).setResizable(false);
        tblData.getColumnModel().getColumn(3).setResizable(false);
        tblData.getColumnModel().getColumn(4).setResizable(false);
        tblData.getColumnModel().getColumn(5).setResizable(false);
    }

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(12, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seller Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

    txtSellerName.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtSellerNameActionPerformed(evt);
        }
    });

    cboPosition.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
    cboPosition.setForeground(new java.awt.Color(0, 0, 255));
    cboPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    cboPosition.setToolTipText("Worker Position in the Sale");
    cboPosition.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboPositionActionPerformed(evt);
        }
    });

    lblWorkerName.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    lblWorkerName.setForeground(new java.awt.Color(51, 102, 255));
    lblWorkerName.setText("Worker Name");

    lblBuyerName.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    lblBuyerName.setForeground(new java.awt.Color(51, 102, 255));
    lblBuyerName.setText("Buyer Name");

    lblPosition.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    lblPosition.setForeground(new java.awt.Color(51, 102, 255));
    lblPosition.setText("Position");

    lblRuc.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
    lblRuc.setForeground(new java.awt.Color(51, 102, 255));
    lblRuc.setText("RUC");

    btnAdd.setBackground(new java.awt.Color(0, 102, 255));
    btnAdd.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
    btnAdd.setForeground(new java.awt.Color(255, 255, 255));
    btnAdd.setText("Add");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddActionPerformed(evt);
        }
    });

    btnSubmit.setBackground(new java.awt.Color(51, 102, 0));
    btnSubmit.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
    btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
    btnSubmit.setText("Submit");
    btnSubmit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSubmitActionPerformed(evt);
        }
    });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBuyerName))))
                .addGap(285, 285, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPosition)
                    .addComponent(lblBuyerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkerName)
                    .addComponent(lblRuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtTitle.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 51, 255));
        txtTitle.setText("Animal Sales Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(114, 114, 114))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitle)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        lblEmail.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 102, 255));
        lblEmail.setText("E-Mail");

        btnAccess.setBackground(new java.awt.Color(204, 204, 204));
        btnAccess.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnAccess.setText("Submit");
        btnAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccess)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAccess))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleName("Seller Data");

        mnuprincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        mnuprincipal.setForeground(new java.awt.Color(255, 255, 255));
        mnuprincipal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jMenu1.setText("Home");
        mnuprincipal.add(jMenu1);

        jMenu2.setText("About");

        mniCredits.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniCredits.setText("Author");
        mniCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreditsActionPerformed(evt);
            }
        });
        jMenu2.add(mniCredits);

        mnuprincipal.add(jMenu2);

        setJMenuBar(mnuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cboPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPositionActionPerformed

    private void rbnCowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnCowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnCowActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Variables
        try {
            String sellerName, buyerName, position="", taxId="-", animalType;
            int quantity;
            double price;
            Map<String, Double> animalResponse;

            sellerName = txtSellerName.getText();
            buyerName = txtBuyerName.getText();
            animalType = this.buttonGroup1.getSelection().getActionCommand();
            quantity = Integer.parseInt(txtAnimalQuantity.getText());
            position = this.cboPosition.getSelectedItem().toString();
            price = Double.parseDouble(txtUnitPrice.getText());
            taxId = txtTaxId.getText();

            // Processing
            AnimalController animalController = new AnimalController();
            animalResponse = animalController.process(animalType, quantity);

            // Display
            Object[] rowData = {buyerName, taxId, sellerName, animalType, quantity, animalResponse.get("Total")};        
            DefaultTableModel tableModel = (DefaultTableModel) this.tblData.getModel();
            tableModel.addRow(rowData);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please complete the entire form before proceeding.");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        try {
            FinishedDayView finishedDay = new FinishedDayView(null, true);
            finishedDay.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please complete the entire form.");
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessActionPerformed
        URL url;
        URLConnection urlCon;
        ImageIcon icon;
        ImageIcon imageIcon;
        String email = txtemail.getText();
        try {
            //67692b385cc73f1b6d6bcb24b13bfc37
            String hash = MD5Util.md5Hex(email.toLowerCase());
            url = new URL("http://www.gravatar.com/avatar/"+hash);
            urlCon = url.openConnection();
            icon = new ImageIcon(url);
            imageIcon = new ImageIcon(icon.getImage().getScaledInstance(label2.getWidth(), label2.getHeight(), Image.SCALE_DEFAULT));
            label2.setIcon(imageIcon);
            label2.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Internet connection problems");
        }
    }//GEN-LAST:event_btnAccessActionPerformed

    private void mniCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreditsActionPerformed
        // TODO add your handling code here:
        try {
            CreditsView credits = new CreditsView(null, true);
            credits.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Error loading.");
        }
    }//GEN-LAST:event_mniCreditsActionPerformed

    private void rbnChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnChickenActionPerformed

    private void rbnHorseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnHorseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnHorseActionPerformed

    private void rbnHenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnHenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnHenActionPerformed

    private void txtSellerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSellerNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccess;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFinish;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboPosition;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType1;
    private javax.swing.JLabel lblType2;
    private javax.swing.JLabel lblType3;
    private javax.swing.JLabel lblType4;
    private javax.swing.JLabel lblType5;
    private javax.swing.JLabel lblType6;
    private javax.swing.JLabel lblType7;
    private javax.swing.JMenuItem mniCredits;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rbnChicken;
    private javax.swing.JRadioButton rbnHorse;
    private javax.swing.JRadioButton rbnHen;
    private javax.swing.JRadioButton rbnCow;
    private javax.swing.JTable tblData;
    private javax.swing.JPanel txtQuantity;
    private javax.swing.JTextField txtAnimalQuantity;
    private javax.swing.JTextField txtBuyerName;
    private javax.swing.JTextField txtUnitPrice;
    private javax.swing.JTextField txtTaxId;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables

    private void initControls() {
        //radio Button
        this.rbnCow.setActionCommand(AnimalController.TYPE_COW);
        this.rbnHorse.setActionCommand(AnimalController.TYPE_HORSE);
        this.rbnHen.setActionCommand(AnimalController.TYPE_HEN);
        this.rbnChicken.setActionCommand(AnimalController.TYPE_CHICKEN);
        //combo
        this.cboPosition.removeAllItems();
        WorkerController controller = new WorkerController();
        for(String item: controller.getPositions()){
            this.cboPosition.addItem(item);
        }
        //Table
    }

}
