/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.net.URL;
import java.net.URLConnection;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controller.AnimalController;
import Controller.EmployeeController;
import Helper.MD5Util;

/**
 *
 * @author Alumno-CT
 */
public class WorkerView extends javax.swing.JFrame {
    DefaultTableModel table;
    /**
     * Creates new form TrabajadorView
     */
    public WorkerView() {
        initComponents();
        initControls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        pnlPrincipal = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JPanel();
        lbltype = new javax.swing.JLabel();
        rbncow = new javax.swing.JRadioButton();
        rbnhorse = new javax.swing.JRadioButton();
        rbnrooster = new javax.swing.JRadioButton();
        rbnchicken = new javax.swing.JRadioButton();
        lbltype1 = new javax.swing.JLabel();
        txtAnimalData = new javax.swing.JTextField();
        lbltype2 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtWorkerName = new javax.swing.JTextField();
        txtBuyerName = new javax.swing.JTextField();
        cboPosition = new javax.swing.JComboBox();
        txtTID = new javax.swing.JTextField();
        lbltype3 = new javax.swing.JLabel();
        lbltype4 = new javax.swing.JLabel();
        lbltype5 = new javax.swing.JLabel();
        lbltype6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbltype7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnAccess = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mnuprincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mniCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farm Sales Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        txtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(51, 51, 255));

        lbltype.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype.setForeground(new java.awt.Color(51, 102, 0));
        lbltype.setText("Type");

        rbncow.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbncow);
        rbncow.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbncow.setText("Cow");
        rbncow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbncowActionPerformed(evt);
            }
        });

        rbnhorse.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbnhorse);
        rbnhorse.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbnhorse.setText("Horse");

        rbnrooster.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbnrooster);
        rbnrooster.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbnrooster.setText("Rooster");
        rbnrooster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnroosterActionPerformed(evt);
            }
        });

        rbnchicken.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbnchicken);
        rbnchicken.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        rbnchicken.setText("Chicken");
        rbnchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnchickenActionPerformed(evt);
            }
        });

        lbltype1.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype1.setForeground(new java.awt.Color(51, 102, 0));
        lbltype1.setText("Amount");

        lbltype2.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype2.setForeground(new java.awt.Color(51, 102, 0));
        lbltype2.setText("Price By Unit");

        javax.swing.GroupLayout txtCantidadLayout = new javax.swing.GroupLayout(txtCantidad);
        txtCantidad.setLayout(txtCantidadLayout);
        txtCantidadLayout.setHorizontalGroup(
            txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltype)
                    .addComponent(rbnhorse)
                    .addComponent(rbnchicken)
                    .addComponent(rbnrooster)
                    .addComponent(rbncow))
                .addGap(61, 61, 61)
                .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltype1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltype2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnimalData)
                    .addComponent(txtUnitPrice))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        txtCantidadLayout.setVerticalGroup(
            txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantidadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtCantidadLayout.createSequentialGroup()
                        .addGroup(txtCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltype)
                            .addComponent(lbltype1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnchicken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbncow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnhorse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnrooster))
                    .addGroup(txtCantidadLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtAnimalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbltype2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Overview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        tblData.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BUYER", "TID", "SELLER", "ANIMAL", "QUANTITY", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setResizable(false);
            tblData.getColumnModel().getColumn(1).setResizable(false);
            tblData.getColumnModel().getColumn(2).setResizable(false);
            tblData.getColumnModel().getColumn(3).setResizable(false);
            tblData.getColumnModel().getColumn(4).setResizable(false);
            tblData.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seller Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        cboPosition.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cboPosition.setForeground(new java.awt.Color(0, 0, 255));
        cboPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPosition.setToolTipText("Tipo de Trabador en la Venta");
        cboPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPositionActionPerformed(evt);
            }
        });

        lbltype3.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype3.setForeground(new java.awt.Color(51, 102, 0));
        lbltype3.setText("Worker's Name");

        lbltype4.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype4.setForeground(new java.awt.Color(51, 102, 0));
        lbltype4.setText("Buyer's Name");

        lbltype5.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype5.setForeground(new java.awt.Color(51, 102, 0));
        lbltype5.setText("Position");

        lbltype6.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype6.setForeground(new java.awt.Color(51, 102, 0));
        lbltype6.setText("Tax ID");

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnComplete.setBackground(new java.awt.Color(51, 102, 0));
        btnComplete.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnComplete.setForeground(new java.awt.Color(255, 255, 255));
        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltype4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltype3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboPosition, 0, 136, Short.MAX_VALUE)
                            .addComponent(lbltype5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltype6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtTID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComplete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltype3)
                            .addComponent(lbltype5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltype4)
                            .addComponent(lbltype6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnComplete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtTitulo.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 102, 0));
        txtTitulo.setText("Farm Sales Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addGap(176, 176, 176))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Consolas", 0, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        lbltype7.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lbltype7.setForeground(new java.awt.Color(51, 102, 0));
        lbltype7.setText("Email");

        btnAccess.setBackground(new java.awt.Color(204, 204, 204));
        btnAccess.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnAccess.setText("Access");
        btnAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccess)
                    .addComponent(lbltype7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbltype7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAccess))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuprincipal.setBackground(new java.awt.Color(255, 255, 255));
        mnuprincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        mnuprincipal.setForeground(new java.awt.Color(255, 255, 255));
        mnuprincipal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jMenu1.setText("Start");
        mnuprincipal.add(jMenu1);

        jMenu2.setText("About");

        mniCreditos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mniCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/21422542.png"))); // NOI18N
        mniCreditos.setText("Autor");
        mniCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreditosActionPerformed(evt);
            }
        });
        jMenu2.add(mniCreditos);

        mnuprincipal.add(jMenu2);

        setJMenuBar(mnuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPositionActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cboPositionActionPerformed

    private void rbncowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbncowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbncowActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Variables
        try {
            String sellerName, buyerName, position = "", taxID = "-", animalType;
            int quantity;
            double price;
            Map<String, Double> animalResponse;
            sellerName = txtWorkerName.getText();
            buyerName = txtBuyerName.getText();
            animalType = this.buttonGroup1.getSelection().getActionCommand();
            quantity = Integer.parseInt(txtAnimalData.getText());
            position = this.cboPosition.getSelectedItem().toString();
            price = Double.parseDouble(txtUnitPrice.getText());
            taxID = txtTID.getText();
            //Process
            AnimalController animalController = new AnimalController();
            animalResponse = animalController.process(animalType, quantity);
            //Show
            Object[] rowData = {buyerName, taxID, sellerName, animalType, quantity, animalResponse.get("Total")};
            table = (DefaultTableModel) this.tblData.getModel();
            table.addRow(rowData);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please complete the entire form from here.");
}

        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        try {
            FinalizedDayView finalized=new FinalizedDayView(null, true);
            finalized.setVisible(true);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please complete the entire form from here.");
        }
        
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void mniCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreditosActionPerformed
        // TODO add your handling code here:
        try {
            
            CreditsView credit=new CreditsView(null, true);
            credit.setVisible(true);
        }catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Error loading image.");
        }
    }//GEN-LAST:event_mniCreditosActionPerformed

    private void rbnchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnchickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnchickenActionPerformed

    private void rbnroosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnroosterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnroosterActionPerformed

    private void btnAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessActionPerformed
        URL url;
        URLConnection urlCon;
        ImageIcon icon;
        ImageIcon resizedIcon;
        String email = txtemail.getText();
        try {
            // Hash the email address using MD5
            String hash = MD5Util.md5Hex(email.toLowerCase());

            // Construct the Gravatar URL
            url = new URL("https://media.licdn.com/dms/image/C4E03AQFmPNfw4hL6xg/profile-displayphoto-shrink_800_800/0/1631584454672?e=2147483647&v=beta&t=lH0132bWEjsbcd3fAcjLOzsbBtVBlg4btMsHW_fUJcY");
            urlCon = url.openConnection();

            // Load the image and resize it
            icon = new ImageIcon(url);
            resizedIcon = new ImageIcon(icon.getImage().getScaledInstance(label2.getWidth(), label2.getHeight(), Image.SCALE_DEFAULT));

            // Set the resized image as the icon for the label
            label2.setIcon(resizedIcon);
            label2.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Internet connection problems");
        }
    }//GEN-LAST:event_btnAccessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WorkerView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccess;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnComplete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboPosition;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lbltype1;
    private javax.swing.JLabel lbltype2;
    private javax.swing.JLabel lbltype3;
    private javax.swing.JLabel lbltype4;
    private javax.swing.JLabel lbltype5;
    private javax.swing.JLabel lbltype6;
    private javax.swing.JLabel lbltype7;
    private javax.swing.JMenuItem mniCreditos;
    private javax.swing.JMenuBar mnuprincipal;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JRadioButton rbnchicken;
    private javax.swing.JRadioButton rbncow;
    private javax.swing.JRadioButton rbnhorse;
    private javax.swing.JRadioButton rbnrooster;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtAnimalData;
    private javax.swing.JTextField txtBuyerName;
    private javax.swing.JPanel txtCantidad;
    private javax.swing.JTextField txtTID;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtUnitPrice;
    private javax.swing.JTextField txtWorkerName;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables

    private void initControls() {
        //radio Button
        this.rbnhorse.setActionCommand(AnimalController.HORSE_TYPE);
        this.rbncow.setActionCommand(AnimalController.COW_TYPE);
        this.rbnrooster.setActionCommand(AnimalController.ROOSTER_TYPE);
        this.rbnchicken.setActionCommand(AnimalController.CHICKEN_TYPE);
        //combo
        this.cboPosition.removeAllItems();
        EmployeeController controller = new EmployeeController();
        for(String item: controller.getPositions()){
            this.cboPosition.addItem(item);
        }
        //Table
        
    }
}
